var initLanguage = function(){

  JSONEditor.defaults.languages.en = {
    button_add_row_title:"Add {{0}}",
    button_collapse:"Inklappen",
    button_delete_all:"Alles",
    button_delete_all_title:"Verwijder alles",
    button_delete_last:"Laatste {{0}}",
    button_delete_last_title:"Verwijder laatste {{0}}",
    button_delete_row_title:"Verwijder {{0}}",
    button_delete_row_title_short:"Verwijder",
    button_expand:"Uitklappen",
    button_move_down_title:"Naar beneden",
    button_move_up_title:"Naar boven",
    error_additionalItems:"Geen extra items toegestaan",
    error_additional_properties:"Geen extra eigenschappen toegestaan: eigenschap {{0}} is echter wel present.",
    error_anyOf:"Waarde moet minimaal overeenkomen met 1 van de verwachte waardes", 
    error_dependency:"Eigenschap {{0}} is nodig",
    error_disallow:"Waarde mag niet type {{0}} zijn",
    error_disallow_union:"Value must not be one of the provided disallowed types",
    error_enum:"Value must be one of the enumerated values",
    error_maxItems:"Value must have at most {{0}} items",
    error_maxLength:"Value must be at most {{0}} characters long",
    error_maxProperties:"Object must have at most {{0}} properties",
    error_maximum_excl:"Value must be less than {{0}}",
    error_maximum_incl:"Value must be at most {{0}}",
    error_minItems:"Value must have at least {{0}} items",
    error_minLength:"Value must be at least {{0}} characters long",
    error_minProperties:"Object must have at least {{0}} properties",
    error_minimum_excl:"Value must be greater than {{0}}",
    error_minimum_incl:"Value must be at least {{0}}",
    error_multipleOf:"Value must be a multiple of {{0}}",
    error_not:"Value must not validate against the provided schema",
    error_notempty:"Value required",
    error_notset:"Property must be set",
    error_oneOf:"Value must validate against exactly one of the provided schemas. It currently validates against {{0}} of the schemas.",
    error_pattern:"Dit veld bevat ongeldige tekens",
    error_required:"Object is missing the required property '{{0}}'",
    error_type:"Value must be of type {{0}}",
    error_type_union:"Value must be one of the provided types",
    error_uniqueItems:"Array must have unique items"
  }
}
